---

- hosts: localhost
  become: true


  tasks:

  - name: Change the Auditbeat configuration
    template: src=templates/auditbeat.yml dest=/etc/auditbeat/auditbeat.yml

  - name: Restart Auditbeat
    service: name=auditbeat state=restarted
