filebeat.prospectors:

#- input_type: log
#  paths:
#    - /var/log/syslog
#  document_type: syslog

- input_type: log
  paths:
    - /var/log/kibana/kibana.log
  document_type: kibana
  json.message_key: log

{% if ansible_architecture == "x86_64" %}
- input_type: log
  paths:
    - /var/lib/docker/containers/{{ myredis_docker_id }}/{{ myredis_docker_id }}-json.log
  document_type: docker
  json.message_key: log
  fields:
    cgroup.id: "{{ myredis_docker_id }}"


processors:
- add_docker_metadata:
    match_fields: ["fields.cgroup.id"]
    host: "unix:///var/run/docker.sock"
{% endif %}


filebeat.modules:
- module: system
- module: nginx


#output.logstash:
#  hosts: ["localhost:5044"]


output.elasticsearch:
  hosts: ["localhost:9200"]
