filebeat.prospectors:

#- input_type: log
#  paths:
#    - /var/log/syslog
#  document_type: syslog

- input_type: log
  paths:
    - /var/log/kibana/kibana.log
  document_type: kibana
  json.message_key: log

{% if ansible_architecture == "x86_64" %}
- input_type: log
  paths:
    - /var/lib/docker/containers/*/*-json.log
  document_type: docker
  json.message_key: log


processors:
- add_docker_metadata: ~
{% endif %}


filebeat.modules:
- module: system
- module: nginx


#output.logstash:
#  hosts: ["localhost:5044"]


output.elasticsearch:
  hosts: ["localhost:9200"]


setup.kibana:
  host: "localhost:5601"


setup.dashboards.enabled: true
