heartbeat.monitors:
- type: http
  urls: ["http://localhost:80"]
  schedule: '@every 10s'
  check.response.status: 200


output.elasticsearch:
  hosts: ["localhost:9200"]


setup.kibana:
  host: "localhost:5601"


setup.dashboards.enabled: true
