packetbeat.interfaces.device: any


packetbeat.flows:
  timeout: 30s
  period: 10s


packetbeat.protocols.icmp:
  enabled: true


packetbeat.protocols.dns:
  ports: [53]
  include_authorities: true
  include_additionals: true


packetbeat.protocols.http:
  ports: [80, 5601]


packetbeat.protocols.redis:
  ports: [6379]


packetbeat.protocols.mongodb:
  ports: [27017]


{% if output == "elasticsearch" %}
output.elasticsearch:
  hosts: ["http://localhost:9200"]
{% endif %}


{% if output == "redis" %}
output.redis:
  hosts: ["localhost:6379"]
  datatype: "list"
  key: "packetbeat"
  db: 0
{% endif %}


setup.kibana:
  host: "localhost:5601"


setup.dashboards.enabled: true
